ceph_docker:
  image: ceph/demo
  net: host
  volumes:
    - .:/root/
  environment:
    MON_IP: ${HOST_IP_ADDR}
    CEPH_PUBLIC_NETWORK: ${NETWORK_CIDR}
    CEPH_DEMO_UID: 'default'
    CEPH_DEMO_ACCESS_KEY: 'accessKey1'
    CEPH_DEMO_SECRET_KEY: 'verySecretKey1'
    CEPH_DEMO_BUCKET: 'default_basket'
