ceph_docker:
  image: ceph/demo
  net: host
  volumes:
    - .:/root/
  environment:
    MON_IP: '[YOUR_LOCAL_IP]]'
    CEPH_PUBLIC_NETWORK: '[YOUR_LOCAL_NETWORK_IP]/24'
    CEPH_DEMO_UID: 'default'
    CEPH_DEMO_ACCESS_KEY: 'accessKey1'
    CEPH_DEMO_SECRET_KEY: 'verySecretKey1'
    CEPH_DEMO_BUCKET: 'default_basket'
